- id: doi:10.1016/j.patter.2023.100703
  type: paper
  description: The first open-source benchmark on deep learning-empowered WiFi sensing.
  date: 2023-03-10
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2666389923000405-gr3.jpg
  buttons:
    - type: github
      text: Github
      link: https://github.com/xyanchen/WiFi-CSI-Sensing-Benchmark
    - type: website
      link: https://www.cell.com/patterns/fulltext/S2666-3899(23)00040-5
  tags:
    - wifi sensing
    - benchmark
